# Generated by Django 5.1.4 on 2024-12-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0002_customer_is_done_customer_timestamp_trip_cities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='vehiculed',
            field=models.BooleanField(default=False),
        ),
    ]
