# Generated by Django 5.1.4 on 2025-01-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0003_trip_vehiculed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=150, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Portable'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cities',
            field=models.CharField(max_length=255, null=True, verbose_name='Villes'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehiculed',
            field=models.BooleanField(default=False, verbose_name='Véhiculé'),
        ),
        migrations.CreateModel(
            name='TexasTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_trip', to='appmain.customer')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='texas_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whole_trips', to='appmain.texastrip'),
        ),
    ]
