# Generated by Django 5.1.4 on 2025-01-02 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0004_alter_customer_email_alter_customer_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_service', models.BooleanField(default=False)),
                ('nbr_days_mobile', models.IntegerField(blank=True, null=True)),
                ('price_mobile', models.FloatField(blank=True, null=True)),
                ('driver_service', models.BooleanField(default=False)),
                ('nbr_days_driver', models.IntegerField(blank=True, null=True)),
                ('price_driver', models.FloatField(blank=True, null=True)),
                ('platinum_service', models.BooleanField(default=False)),
                ('nbr_days_platinum', models.IntegerField(blank=True, null=True)),
                ('price_platinum', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('payment_type', models.CharField(default='Credit card', max_length=20)),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Paid'), ('3', 'Rejected')], default='1', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='appmain.customer')),
                ('texas_trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_invoice', to='appmain.texastrip')),
            ],
        ),
    ]
