# Generated by Django 5.1.4 on 2025-01-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0005_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='texastrip',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
