# Generated by Django 5.1.4 on 2025-01-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0006_texastrip_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_called',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_mailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
