# Generated by Django 5.1.4 on 2025-01-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0009_invoice_terms_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='terms_accepted',
            new_name='terms_of_sale_accepted',
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms_of_sale_accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
