# Generated by Django 5.1.4 on 2025-01-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0010_rename_terms_accepted_invoice_terms_of_sale_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
