# Generated by Django 5.1.4 on 2025-01-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0013_invoice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
