# Generated by Django 5.1.4 on 2025-01-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0014_invoice_stripe_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='price_driver',
            new_name='driver_price_excl_tax',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='price_mobile',
            new_name='mobile_price_excl_tax',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='price_platinum',
            new_name='platinum_price_excl_tax',
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_excl_tax',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
