# Generated by Django 5.1.4 on 2025-01-17 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0018_fileforimage_alter_customer_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.ImageField(upload_to='images/best_of_cities/')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='appmain.fileforimage')),
            ],
        ),
    ]
