# Generated by Django 5.1.4 on 2025-01-17 14:52

import appmain.services.attraction_service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0019_attraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='image_url',
            field=models.ImageField(upload_to=appmain.services.attraction_service.upload_to_file_for_image),
        ),
    ]
