# Generated by Django 5.1.4 on 2025-01-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0020_alter_attraction_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
