# Generated by Django 5.1.4 on 2025-01-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0021_attraction_description_en_attraction_description_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileforimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
