# Generated by Django 5.1.4 on 2025-01-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0022_fileforimage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
