# Generated by Django 5.1.4 on 2025-01-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0023_attraction_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDisplayTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
