# Generated by Django 5.1.4 on 2025-01-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0024_imagedisplaytheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Catégories'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Catégories'),
        ),
        migrations.AddField(
            model_name='imagedisplaytheme',
            name='theme_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imagedisplaytheme',
            name='theme_fr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
