# Generated by Django 5.1.4 on 2025-01-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0025_category_name_en_category_name_fr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_fr', models.CharField(max_length=50, null=True)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('EIN', models.CharField(blank=True, max_length=20, null=True)),
                ('SIREN', models.CharField(blank=True, max_length=20, null=True)),
                ('legal_structure', models.CharField(blank=True, max_length=30, null=True)),
                ('legal_structure_fr', models.CharField(blank=True, max_length=30, null=True)),
                ('legal_structure_en', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(max_length=155)),
                ('tax_info', models.CharField(max_length=6)),
                ('tax_info_fr', models.CharField(max_length=6, null=True)),
                ('tax_info_en', models.CharField(max_length=6, null=True)),
                ('tax_math', models.FloatField(blank=True, null=True)),
                ('tax_math_fr', models.FloatField(blank=True, null=True)),
                ('tax_math_en', models.FloatField(blank=True, null=True)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_fr', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_en', models.CharField(blank=True, max_length=15, null=True)),
                ('instagram', models.CharField(max_length=50)),
                ('instagram_fr', models.CharField(max_length=50, null=True)),
                ('instagram_en', models.CharField(max_length=50, null=True)),
                ('is_in_texas', models.BooleanField(default=False)),
            ],
        ),
    ]
