# Generated by Django 5.1.4 on 2025-01-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0026_companyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='texastrip',
            name='package',
            field=models.IntegerField(choices=[(1, 'autonome'), (2, 'chauffeur privée'), (3, 'platinum')], default=1),
        ),
    ]
