# Generated by Django 5.1.4 on 2025-01-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0028_alter_trip_end_date_alter_trip_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='vehiculed',
        ),
        migrations.AddField(
            model_name='trip',
            name='nbr_days_driver',
            field=models.IntegerField(default=0, max_length=3, verbose_name='Nombre de jour de service'),
        ),
    ]
