# Generated by Django 5.1.4 on 2025-02-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0030_alter_trip_nbr_days_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.DateTimeField(auto_created=True)),
                ('service_name', models.CharField(max_length=50)),
                ('service_name_fr', models.CharField(max_length=50, null=True)),
                ('service_name_en', models.CharField(max_length=50, null=True)),
                ('price_excl_tax', models.FloatField()),
                ('price_excl_tax_fr', models.FloatField(null=True)),
                ('price_excl_tax_en', models.FloatField(null=True)),
                ('main_tax_info', models.CharField(max_length=6)),
                ('main_tax_info_fr', models.CharField(max_length=6, null=True)),
                ('main_tax_info_en', models.CharField(max_length=6, null=True)),
                ('main_tax_math', models.FloatField(blank=True, null=True)),
                ('main_tax_math_fr', models.FloatField(blank=True, null=True)),
                ('main_tax_math_en', models.FloatField(blank=True, null=True)),
                ('main_tax_name', models.CharField(blank=True, max_length=100, null=True)),
                ('main_tax_name_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('main_tax_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('second_tax_info', models.CharField(max_length=6)),
                ('second_tax_info_fr', models.CharField(max_length=6, null=True)),
                ('second_tax_info_en', models.CharField(max_length=6, null=True)),
                ('second_tax_math', models.FloatField(blank=True, null=True)),
                ('second_tax_math_fr', models.FloatField(blank=True, null=True)),
                ('second_tax_math_en', models.FloatField(blank=True, null=True)),
                ('second_tax_name', models.CharField(blank=True, max_length=100, null=True)),
                ('second_tax_name_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('second_tax_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('is_obsolete', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='texastrip',
            name='package',
            field=models.IntegerField(choices=[(1, 'autonome'), (2, 'chauffeur privé'), (3, 'platinum')], default=1),
        ),
    ]
