# Generated by Django 5.1.4 on 2025-02-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0032_rename_prices_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='main_tax_info',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='price',
            name='main_tax_info_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='main_tax_info_fr',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='second_tax_info',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='price',
            name='second_tax_info_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='second_tax_info_fr',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
