# Generated by Django 5.1.4 on 2025-02-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0033_alter_price_main_tax_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='is_obsolete',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='second_tax_info',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='second_tax_info_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='second_tax_info_fr',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
