# Generated by Django 5.1.4 on 2025-02-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0035_invoice_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10)),
                ('target', models.IntegerField(choices=[(1, 'autonome'), (2, 'chauffeur privé'), (3, 'platinum')], default=1)),
                ('rate', models.CharField(blank=True, max_length=6, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
