# Generated by Django 5.1.4 on 2025-02-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0037_alter_invoice_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_incl_discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
