# Generated by Django 5.1.4 on 2025-03-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0038_invoice_total_incl_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price_excl_tax2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='price_excl_tax3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
