# Generated by Django 5.1.4 on 2025-03-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0039_price_price_excl_tax2_price_price_excl_tax3'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price_excl_tax2_en',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='price_excl_tax2_fr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='price_excl_tax3_en',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='price_excl_tax3_fr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
