# Generated by Django 5.1.4 on 2025-03-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0040_price_price_excl_tax2_en_price_price_excl_tax2_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='distance_allowance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='distance_allowance_en',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='distance_allowance_fr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
