# Generated by Django 5.1.4 on 2025-03-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0041_price_distance_allowance_price_distance_allowance_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
