# Generated by Django 5.1.4 on 2025-03-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0042_price_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='description_es_mx',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='title_es_mx',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_mx',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Catégories'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='instagram_es_mx',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='legal_structure_es_mx',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='name_es_mx',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phone_es_mx',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tax_info_es_mx',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tax_math_es_mx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagedisplaytheme',
            name='theme_es_mx',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='distance_allowance_es_mx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='main_tax_info_es_mx',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='main_tax_math_es_mx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='main_tax_name_es_mx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='price_excl_tax2_es_mx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='price_excl_tax3_es_mx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='price_excl_tax_es_mx',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='second_tax_info_es_mx',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='second_tax_math_es_mx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='second_tax_name_es_mx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='service_name_es_mx',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
