# Generated by Django 5.1.4 on 2025-03-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0043_attraction_description_es_mx_attraction_title_es_mx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction',
            old_name='description_es_mx',
            new_name='description_es',
        ),
        migrations.RenameField(
            model_name='attraction',
            old_name='title_es_mx',
            new_name='title_es',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_es_mx',
            new_name='name_es',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='instagram_es_mx',
            new_name='instagram_es',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='legal_structure_es_mx',
            new_name='legal_structure_es',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='name_es_mx',
            new_name='name_es',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='phone_es_mx',
            new_name='phone_es',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='tax_info_es_mx',
            new_name='tax_info_es',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='tax_math_es_mx',
            new_name='tax_math_es',
        ),
        migrations.RenameField(
            model_name='imagedisplaytheme',
            old_name='theme_es_mx',
            new_name='theme_es',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='distance_allowance_es_mx',
            new_name='distance_allowance_es',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='main_tax_info_es_mx',
            new_name='main_tax_info_es',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='main_tax_math_es_mx',
            new_name='main_tax_math_es',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='main_tax_name_es_mx',
            new_name='main_tax_name_es',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='price_excl_tax2_es_mx',
            new_name='price_excl_tax2_es',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='price_excl_tax3_es_mx',
            new_name='price_excl_tax3_es',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='price_excl_tax_es_mx',
            new_name='price_excl_tax_es',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='second_tax_info_es_mx',
            new_name='second_tax_info_es',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='second_tax_math_es_mx',
            new_name='second_tax_math_es',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='second_tax_name_es_mx',
            new_name='second_tax_name_es',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='service_name_es_mx',
            new_name='service_name_es',
        ),
    ]
