# Generated by Django 5.1.4 on 2025-05-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0044_rename_description_es_mx_attraction_description_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sign_up_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
