# Generated by Django 5.1.4 on 2025-05-22 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0045_remove_companyinfo_ein_remove_companyinfo_siren_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='nbr_days_mobile',
        ),
    ]
